[project]
name = "quotes"
version = "0.1.0"
description = "Dan's favorite quotes"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastapi[standard]>=0.121.0",
    "greenlet>=3.2.4",
    "sqlalchemy>=2.0.44",
]
