[project]
name = "flasktesting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.3.2",
    "duckdb-engine>=0.17.0",
    "flask>=3.1.1",
    "flask-sqlalchemy>=3.1.1",
    "sqlalchemy>=2.0.43",
]
